---
title: "Model proposal"
author: "Borg \\and Gentile Passaro \\and Hermo"
date: "`r format(Sys.time(), '%B %d , %Y')`"
output: 
  pdf_document
header-includes:
  - \newtheorem{prop}{Proposition}
  - \newtheorem{cor}{Corollary}
  - \newenvironment{proof}{\textit{Proof:}}{\hfill$\square$}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this note we lay down a simply model that exemplifies the potential opposing 
effects of the experienced versus the statutory MW and makes clear the mechanism
behind ``transfers of income across ZIP codes'' that we have in mind.

While the model does not allow for welfare calculations, it does permit an intuitive
discussion of the mechanisms that may drive the effects and of identification.
We think it can potentially be a (small) contribution, since it exploits the distribution 
of workers' residence and workplaces (which has started to differ more over time, 
as noted in the literature --see, e.g.,  
[Monte, Redding, and Rossi-Hansberg 2018](https://www.aeaweb.org/articles?id=10.1257/aer.20151507),
Figure 1) to propose an intuitive way to study the consequences and spillovers of 
local MWs (see [Dube and Lindner 2021](https://www.aeaweb.org/articles?id=10.1257/jep.35.1.27)).


Some mechanisms are assumed below, such as the negative effect of a residence MW 
on income. We leave the micro-foundations of such mechanisms to the development of 
a more complete model in a follow-up project.


# A simple model of a ZIP code's housing market

## Set-up

Imagine there are a set of zipcodes $\mathcal{Z}$. 
There is an exogenously given distribution of people with differing
residence $n$ and workplace $i$ locations.
Denote by $L_{n i}$ the number of people from $n$ who work in $i$;
by $L_n = \sum_{i \in \mathcal{Z}} L_{n i}$ and $L_i = \sum_{n \in \mathcal{Z}} L_{n i}$ 
the number of residents in $n$ and workers in $i$, respectively;
and by $\mathcal{L}=\sum_{n \in \mathcal{Z}}L_n=\sum_{i \in \mathcal{Z}}L_i$
the total number of workers.

Workers are characterized by residence and workplace location.
We let $y_{ni} = y_{ni}(\underline{w}^L, \underline{w}^R)$ denote disposable income 
of workers in the $(n, i)$ cell, which depends on the minimum wage in the workplace 
$\underline{w}^L$ and the minimum wage in the residence $\underline{w}^R$.
We assume that

$$
\frac{d y_{ni}}{d \underline{w}^L} > 0 , 
\quad 
\frac{d y_{ni}}{d \underline{w}^R} < 0
\quad \quad  \forall (n,i) ,
$$

so that workplace minimum wages increase disposable income of these workers, whereas 
residence ones lower it.

We denote housing demand by the $(c,i)$ group as $H_{ni} \left(r_n, y_{ni} \right)$, 
where $r_n$ represents rents. The derivatives of housing demand are

$$
\frac{d H_{ni} (r_n, y_{ni})}{d r} < 0, 
  \quad \quad 
\frac{d H_{ni} (r_n, y_{ni})}{d y} > 0 .
$$

Finally, $D_n (r_n)$ is a measure of housing units supplied in $n$, with 
$\frac{d D_n (r_n)}{d r} > 0$.

Note that we let the effect of MWs on incomes unspecified, and pose no restriction
on the $y_{ni} \left(\cdot, \cdot\right)$ function other than the signs of the response
to workplace and residence minimum wage changes.
An increase in the wage in some workplace location increases disposable income
because workers earn a higher wage.
However, if there is a minimum wage in the residence location disposable income 
goes down. The reason is that local prices go up in that case.

Note that, for those who work and reside in $n$ with minimum wage $\underline{w}_n$, 
we have $$y_{nn} = y(\underline{w}_n, \underline{w}_n) .$$

## Equilibrium and Comparative Statics

The local housing market for ZIP code $n$ is in equilibrium if total demand for
housing equals total supply. Formally,

$$ \sum_{i\in\mathcal{Z}} L_{ni} H_{ni} (r_n, y_{ni}) =  D_n (r_n) .$$

Here is a proposition.

\begin{prop}\label{prop:exp_mw}
  Under the assumptions of 
  (i) fixed distribution of workers across residence and  workplace ZIP codes, 
  (ii) disposable income in a ZIP code is increasing in workplace 
  MW, and 
  (iii) disposable income in a ZIP code is decreasing in residence MW,
  we have that
  
  \begin{enumerate}
    \item conditional on changes in the statutory MW, changes in the experienced MW increase rents.
    \item conditional on changes in the experienced MW, changes in the statutory MW decrease rents.  
  \end{enumerate}
\end{prop}

\begin{proof}
  Fully differentiate the market clering condition with respect to $\ln r_n$, 
  $\ln \underline{w}_i$ for all $i$ and $\ln \underline{w}_n$ to get
  
  $$
  \sum_i L_{ni} \frac{d H_{ni}}{d r} r_n d \ln r_n
  + \sum_i L_{ni} \frac{d H_{ni}}{d y} y_{ni} 
      \left( \frac{d y_{ni}}{d \underline{w}^L} \underline{w}_i d \ln \underline{w}_i 
           + \frac{d y_{ni}}{d \underline{w}^R} \underline{w}_n d \ln \underline{w}_n \right)
  = \frac{d D_n}{d r_n} r_n d \ln r_n
  $$
  
  We can transform this expression into elasticities as follows. First, divide on 
  both sides by the equilibrium condition $\sum_i L_{ni} H_{ni} =  D_n$ and multiply
  and divide in the first  two terms by $L_n$. This leads to
  $$
  \sum_i \pi_{ni} \xi_{ni}^r d \ln r_n
  + \sum_i \pi_{ni} \xi_{ni}^y \epsilon_{ni}^L d \ln \underline{w}_i 
  + \sum_i \pi_{ni} \xi_{ni}^y \epsilon_{ni}^R d \ln \underline{w}_n
  = \eta_n d \ln r_n
  $$
  
  where 
  $\pi_{ni} = \frac{L_{ni}}{L_n}$ represent the share of workers from $n$ working in $i$;
  $\xi_{ni}^r = \frac{d H_{ni}}{d r} \frac{r_n}{\sum_i \pi_{ni}H_{ni}}$ and 
  $\xi_{ni}^y = \frac{d H_{ni}}{d y} \frac{y_{ni}}{\sum_i \pi_{ni}H_{ni}}$ 
  are the elasticities of housing demand to rents and income evaluated at the 
  average housing demand of ZIP code $n$;
  $\epsilon_{ni}^L = \frac{d y_{ni}}{d \underline{w}^L} \frac{\underline{w}_i}{y_{ni}}$ and
  $\epsilon_{ni}^R = \frac{d y_{ni}}{d \underline{w}^R} \frac{\underline{w}_n}{y_{ni}}$
  are the elasticities of disposable income of group $(n, i)$ to changes in either workplace
  or residence minimum wage; and
  $\eta_n = \frac{d D_n}{d r_n} \frac{r_n}{D_n}$ is the elasticity of housing supply
  in ZIP code $n$.
  
  Solving for $d \ln r_n$ in the above expression we can already see that a workplace
  MW unambiguously increases rents (as $\epsilon_{ni}^L > 0$), whereas a
  residence MW (``statutory'') increase will have an unconditional muted effect,\footnote{The sign 
  of the effect depends on the sign of $\pi_{nn} \epsilon_{nn}^L + \sum_i \pi_{ni} \epsilon_{ni}^R$.
  If the decrease in disposable income in $n$ is strong enough (second term), then 
  rents will go down.} and a negative effect conditional on the experienced MW.
  This completes the proof.
  
  To simplify further, assume that elasticities of rents to disposable income and 
  disposable income to MWs don't vary by workplace location, so that 
  $\xi_{ni}^y=\xi_n^y$, $\epsilon_{ni}^L = \epsilon_n^L$ and $\epsilon_{ni}^R = \epsilon_n^R$ 
  $\forall i \in \mathcal{Z}$. Then, we can write
  
  \begin{equation}\label{eq:reduced-form}
  d \ln r_n = 
    \frac{\xi_n^y\epsilon_n^L}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r} \sum_i \pi_{ni} d \ln \underline{w}_i +
    \frac{\xi_n^y\epsilon_n^R}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r} d \ln \underline{w}_n .
  \end{equation}
  
  The first term on the right-hand side represents the effect of experienced (log) 
  MW changes, 
  whereas the second one represents statutory MW changes. 
  As $\epsilon_n^L > 0$ and $\epsilon_n^R<0$, 
  the former has a positive partial effect on rents and the latter a negative one.
  
\end{proof}

Equation \eqref{eq:reduced-form} makes it clear that, given reasonable assumptions 
on the direction of changes in disposable income following a MW change, the two MW 
measures will differ.
Under the interpretation that changes in income due to residence MWs reflect the 
confounding influence of changing local prices, 
we interpret the first coefficient in equation \eqref{eq:reduced-form} as the "true" 
elasticity of rents to the MW, since it solely reflects the increases in income following 
the enactment of the policy. Denote this parameter by 
$\beta := \frac{\xi_n^y\epsilon_n^L}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r}$.
The following corollary makes it clear that, absent variation in workplace and residence
MWs, then $\beta$ is not identified.

\begin{cor}\label{cor:identification}
  Assume that elasticities of rents to disposable income and disposable income to 
  MWs don't vary by workplace location, so that equation \eqref{eq:reduced-form}
  holds. If $d \ln \underline{w}_i = d \ln \underline{w}$ for all $i\in\mathcal{Z}$,
  then $\beta$ is not identified.
\end{cor}

\begin{proof}
  Imposing the assumption $d \ln \underline{w}_i = d \ln \underline{w}$ 
  on equation \eqref{eq:reduced-form} yields:
  
  $$
  d \ln r_n = 
    \frac{\xi_n^y\epsilon_n^L\sum_i \pi_{ni} + \xi_n^y\epsilon_n^R}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r} d \ln \underline{w} .
  $$
  
  It is evident that the coefficient is not equal to $\beta$.
  
\end{proof}

A proposition like above would allow us to connect to the city minimum wages literature.

Also, studies that use more aggregated data may not dispose of this variation and, 
thus, make it impossible to separate the two. Therefore, they estimates may be biased 
as they don't account for variation in residence prices.

## Extending the model to discuss empirical approach

This section illustrates how the simple model presented above could be connected to
the empirical model.

Imagine that the econometrician observes data 
$\left\{\{r_{nt}, \underline{w}_{nt}\}_{t=1}^T\right\}_{n\in\mathcal{Z}}$ and 
wants to learn the effect of the MW on rents attributable to an increase in income.
Suppose also that some unobserved ZIP-code-specific factors $u_{nt}$ affect housing 
demand.

Rents are determined in spot housing markets in each ZIP code by the market-clearing
condition

$$ \sum_{i\in\mathcal{Z}} L_{ni} H_{n} (r_{nt}, y_{nit}, u_{nt}) =  D_n (r_{nt}) .$$
where the subscripts make it clear that the distribution of workers and the 
housing demand and supply functions are taken as given. Also, we assume that housing 
demand does not vary by workplace $i$.

Following the procedure in the proof of \ref{prop:exp_mw} we can write
\begin{equation}\label{eq:reduced-form-time}
  d \ln r_{nt} = 
    \frac{\xi_n^y\epsilon_n^L}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r} \sum_i \pi_{ni} d \ln \underline{w}_{it} +
    \frac{\xi_n^y\epsilon_n^R}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r} d \ln \underline{w}_{nt} +
    \frac{\xi_n^u}{\eta_n - \sum_i\pi_{ni}\xi_{ni}^r} d \ln u_{nt} .
\end{equation}

This equation neatly connects with our empirical model. For example, it is clear 
that under the assumption that MWs are strictly exogenous, so that
$$
E\left(\underline{w}_{n\tau} \cdot u_{nt} \right) = 0 \quad \forall \tau
$$
holds for every period and zipcode, a regression of rents on the statutory and
experienced MW would provide unbiased estimates of both structural coefficients.

