---
title: "Benchmarking Advanced"
author: "The MW-n-Rents Guys"
date: "`r format(Sys.time(), '%B %d , %Y')`"
output: 
  pdf_document:
    extra_dependencies: ["dsfont"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this note I lay down a simply model that exemplifies the potential different 
effects of the experienced versus the statutory MW.

## 1. Model Set-up

Imagine there are a set of zipcodes $\mathcal{Z}$. 
There is an exogenously given distribution of people with differing
residence $n$ and workplace $i$ locations.
Denote by $L_{n i}$ the number of people from $n$ who work in $i$;
by $L_n = \sum_{i \in \mathcal{Z}} L_{n i}$ and $L_i = \sum_{n \in \mathcal{Z}} L_{n i}$ 
the number of residents in $n$ and workers in $i$, respectively;
and by $\mathcal{L}=\sum_{n \in \mathcal{Z}}L_n=\sum_{i \in \mathcal{Z}}L_i$
the total number of workers.

Furthermore, let:

- $\underline{w}_i$ be the wage paid in location $i$; 
- $H_n \left(r_n, \bar{y}_n \right)$ be demand for housing in $n$, where $r_n$ represents 
rents, and $\bar{y}_n$ is disposable income per capita available in $n$ (defined below);
- $D_n (r_n)$ be the measure of housing units supplied in $n$.

The derivatives of housing demand are

$$
\frac{d H_n (r_n, \bar{y}_n)}{d r} < 0, 
  \quad \quad 
\frac{d H_n (r_n, \bar{y}_n)}{d \bar{y}_n} > 0 .
$$

whereas housing supply is increasing in rents, so $\frac{d D_n (r_n)}{d r_n} > 0$.

Per capita disposable income is defined as a weighted average of income generated
in workplace locations of residents of $n$:

$$ 
\bar{y}_n = \sum_{i \in \mathcal{Z}} \pi_{ni} y_{ni} , 
  \quad \ \quad 
\pi_{ni} := \frac{L_{ni}}{L_n}
$$

where $y_{ni}$ is disposable income of workers residing in $n$ and working in $i$.
This, in turn, depends on the minimum wage paid in the workplace $i$ and the one 
paid in $n$, so that $y_{ni} = y(\underline{w}^L, \underline{w}^R)$ and 

$$
\frac{d y}{d \underline{w}^L} > 0 , 
\quad \quad 
\frac{d y}{d \underline{w}^R} < 0 ,
$$

where we use $(\underline{w}^L, \underline{w}^R)$ to avoid potentially confusing 
indexes in the defintion. We also, for simplicity, let $y(\cdot)$ be the the same 
across places.

Note that we let the effect of MWs on incomes unspecificed. We only ask that workplace 
minimum wages increase incomes, whereas residence ones decrease them.
An increase in the wage in some workplace location increases disposable income
because workers earn a higher wage. 
However, if there is a minimum wage in the residence location disposable income 
goes down. The reason is that local prices go up in that case.

Note that, for those who work and reside in $n$ with minimum wage $\underline{w}$, 
we have $$y_{nn} = y(\underline{w}_n, \underline{w}_n) .$$


## 2. Equilibrium and Comparative Statics

The local housing market for ZIP code $n$ is in equilibrium if

$$ H_n (r_n, \bar{y}_n) =  D_n (r_n) .$$
The question we want to ask is the following: what is the effect of increasing
the wage in location $j \neq n$ (by imposing a MW)? What if there is an increase 
in the MW in $n$? What if the minimum wage increases in a set of locations 
$\mathcal{J} \subset \mathcal{Z}$?

### 2.1. Increase in minimum wage in a different location

Write the condition as 

$$ H_n \left(e^{\ln r_n}, 
  \sum_{i \in \mathcal{Z}} \pi_{ni} y(e^{\ln \underline{w}_i}, e^{\ln \underline{w}_n})\right) 
  =  D_n (e^{\ln r_n}) $$

and fully differentiate wrt $\ln r_n$, and $\ln w_j$ for some $j\neq n$ to get

$$ 
\frac{d H_n}{d r_n} r_n d \ln r_n 
  + \frac{d H_n}{d y_n} \frac{d y_{nj}}{d \underline{w}^L} 
              \underline{w}_j \pi_{nj} d \ln \underline{w}_j
  = \frac{D_n}{d r_n} r_n d \ln r_n
$$
Re-arranging, we get
\begin{equation}\label{eq:mw_other}
  \frac{d \ln r_n}{d \ln \underline{w}_j} 
  = \frac{\pi_{nj} \frac{d H_n}{d y_n} \frac{d y_{nj}}{d \underline{w}^L}}
          {\left(\frac{D_n}{d r_n} - \frac{d H_n}{d r_n}\right)}
    \frac{\underline{w}_j}{r_n}
\end{equation}

Since $\frac{d H_n}{d r_n} < 0$, we have that $\frac{d \ln r_n}{d \ln \underline{w}_j} > 0$.
When the MW increases in workplace $j \neq n$, rents in residence ZIP code $n$
go up.

### 2.2. Increase in wages in residence

Now, we assume that the MW increases marginally in $n$ from an initial level of 
$\underline{w}_n$. 
This, in turn, affects disposable income of those living there through both 
arguments of the function $y(\cdot, \cdot)$.
Fully differentiate the market-clearing condition wrt to $\ln r_n$ and 
$\ln \underline{w}_n$ to get

$$ 
\frac{d H_n}{d r_n} r_n d \ln r_n 
  + \frac{d H_n}{d y_n} \underline{w}
        \left( \frac{d y_{nn}}{d \underline{w}^L} \pi_{nn} + \frac{d y_{nn}}{d \underline{w}^R} \right)
        d \ln \underline{w}
  = \frac{D_n}{d r_n} r_n d \ln r_n
$$

We are interested in the elasticity

\begin{equation}\label{eq:mw_residence}
  \frac{d \ln r_n}{d \ln \underline{w}}
  = \frac{\frac{d H_n}{d y_n}
            \left( \frac{d y_{nn}}{d \underline{w}^L} \pi_{nn} + \frac{d y_{nn}}{d \underline{w}^R} \right)}
          {\left(\frac{D_n}{d r_n} - \frac{d H_n}{d r_n}\right)}
    \frac{\underline{w}_n }{r_n}
\end{equation}

It is easy to see that, in this case, the sign of the derivative is ambigous. 
The term $\left( \frac{d y_{nn}}{d \underline{w}^L} \pi_{nn} 
                + \frac{d y_{nn}}{d \underline{w}^R} \right)$
represents the change in per capita disposable income in ZIP code $n$.
If it's positive, so that the increase in wages of local workers is larger than
the negative effect through raising local prices, 
then $\frac{d \ln r_n}{d \ln \underline{w}_n} > 0$.
On the other hand, if it's negative and local prices increase a lot, lowering 
disposable income, we will have $\frac{d \ln r_n}{d \ln \underline{w}_n} < 0$.

### 2.3. Increase in wages in multiple workplace locations

We assume that the MW increases marginally in a subset of locations $\mathcal{J}$,
where $n \notin \mathcal{J}$, from the level $\underline{w}$ common to all of them.
Fully differentiate the market-clearing condition wrt to $\ln r_n$ 
and $\ln \underline{w}$, $j \in \mathcal{J}$, to get

$$
\frac{d H_n}{d r_n} r_n d \ln r_n 
  + \frac{d H_n}{d y_n} \sum_{j \in \mathcal{J}}
                \frac{d y_{nj}}{d \underline{w}^L} \underline{w} \pi_{nj} d \ln \underline{w}
  = \frac{D_n}{d r_n} r_n d \ln r_n .
$$

The elasticity of rents to the MW is

\begin{equation}\label{eq:mw_many_workplace}
  \frac{d \ln r_n}{d \ln \underline{w}}
  = \frac{\frac{d H_n}{d y_n} \sum_{j \in \mathcal{J}} \frac{d y_{nj}}{d \underline{w}^L} \pi_{nj}}
          {\left(\frac{D_n}{d r_n} - \frac{d H_n}{d r_n}\right)}
    \frac{\underline{w}}{r_n}
\end{equation}

The effect is unambigously positive. Furthermore, the more workers from $n$
work in locations $j \in \mathcal{J}$, the stronger the effect will be.

### 2.4. Increase in wages in multiple workplace locations and residence

What if there is a MW increase in locations 
$j\in \tilde{\mathcal{J}} = \mathcal{J} \cup \{n\}$ from a common level $\underline{w}$. 
In that case, the derivative becomes

$$ 
\frac{d H_n}{d r_n} r_n d \ln r_n 
  + \frac{d H_n}{d y_n} 
  \left(\sum_{j \in \mathcal{J}} 
                \frac{d y_{nj}}{d \underline{w}^L} \pi_{nj} 
                + \frac{d y_{nn}}{d \underline{w}^R} \right) \underline{w} d \ln \underline{w}
  = \frac{D_n}{d r_n} r_n d \ln r_n .
$$


Then, our elasticity is

\begin{equation}\label{eq:mw_many_workplace_residence}
  \frac{d \ln r_n}{d \ln \underline{w}}
  = \frac{\frac{d H_n}{d y_n} \left(\sum_{j \in \mathcal{J}} 
                      \frac{d y_{nj}}{d \underline{w}^L} \pi_{nj} 
                      + \frac{d y_{nn}}{d \underline{w}^R} \right)}
          {\left(\frac{D_n}{d r_n} - \frac{d H_n}{d r_n}\right)}
    \frac{\underline{\tilde{w}}}{r_n}
\end{equation}

The sign of the effect will depend on the sign of
$\left(\sum_{j \in \mathcal{J}}
    \frac{d y_{nj}}{d \underline{w}^L} \pi_{nj}
    + \frac{d y_{nn}}{d \underline{w}^R} \right)$.

If many workers work in places with MW increases, then the elasticity will be positive.

Being more careful about how to write this expression it seems that we can make 
the experienced and statutory MW show up there.

## 3. Conclusion and Potential Extensions

- I conjecture that writing more carefully the expresions will likely make the change 
in experienced MW arise there.

- Model assumes that, for some reason, local MWs lower disposable income. A simple 
local goods market could be written down to justify this.

- Assuming constant elasticity functions would simplify the expressions and allow
to write everything in terms of elasticities.

