---
title: "Model for ``Do Minimum Wages Increase Rents?   \n
        Evidence from U.S. ZIP codes using High Frequency Data''"
author: "Borg, Gentile, Hermo"
date: "`r format(Sys.time(), '%B %d , %Y')`"
output: 
  pdf_document:
    extra_dependencies: ["amsmath", "dsfont"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In this note we attempt to develop an urban model for the project.
The model should:

- Make more transparent the mechanisms behind our effect.
- Allow for welfare calculations
- Maybe, justify the experienced MW

## 1. Set-up

Consider a metropolitan area composed by $Z$ ZIP codes, indexed by $n$ and $i$.
There are two types of workers $s \in \{\ell, h\}$, who maximize utility by chosing 
a residence-workplace pair $(n, i)$. 
They also consume a tradable good.
The economy is populated by a representative firm at each ZIP code $i\in Z$ with
monopsony power.
The firm produces the tradable good using both types of labor as inputs.

### 1.1. Workers

We assume that preferences are Cobb-Douglas, so that the utility of residence-workplace
pair $(n, i)$ for worker $\omega$ of type $S$ is

$$
U_{n i \omega} = b_{n i \omega}\frac{B_i}{d_{n i}}
              \left(\frac{C_{n \omega}}{\alpha}\right)^{\alpha}
              \left(\frac{H_{n \omega}}{1-\alpha}\right)^{1-\alpha}
$$

where
$b_{n i \omega}$ is an idiosyncratic shock at the $(n, i)$ level;
$B_{i}$ represents workplace amenities;
$d_{n i}$ is iceberg commuting cost between residence $n$ and workplace $i$;
$C_{n \omega}$ and $H_{n \omega}$ represent consumption and housing, respectively;
and $1-\alpha \in (0, 1)$ is the share spent on housing.

Letting the price of consumption be the numeraire, and $Q_n$ denote the price of 
housing,the budget constraint of a worker of type $s \in \{\ell, h\}$ who works 
in $i$ is

$$
w^s_i = C_{nw} + Q_n H_{n \omega}
$$
<!-- Notes: 
- Can also include a residence amenities $B_i$ term in utility
- Budget constraint could include residence based subsidies
- For now I don't include unemployment (Perez Perez includes it)
- Papers such as Ahlfeldt et al (2015) use varieties for defining C_{n\omega}.
-->

Note that the wage doesn't depend on the worker's identity.
As a result, the solution of the maximization problem will be independent of it too.

Timinig is as follows. 
The worker enters a metropolitan area and observes draws $b_{n i \omega}$ for every
workplace-residence pair.
Conditional on these, workers maximize utililty with respect to the budget constraint
for every $(i, n)$.
As shown in Appendix A, this results in indirect utility

\begin{equation}\label{eq:indirect-utility}
u_{n i}^s = \frac{b_{n i} B_i w_i^s}
                {d_{n i} Q_n^{1 - \alpha}}
\end{equation}
where we dropped the $\omega$ sub-index because the solution is independent of the 
worker's identity.

Finally, workers decide a workplace and residence location by selecting pair that 
yields a highest level of utility.

Following Eaton and Kortum (2002), we assume that the $b_{n i}$ is drawn independently
from a Fréchet distribution:

$$
G_{n i}^{s}(b) = e^{-T_n^s X_i^s} b^{-\epsilon} 
\quad \quad 
T_n^s > 0, X_i^s > 0, \epsilon > 1 \ \forall s.
$$

The variables $T_n^s$ and $X_i^s$ are parameters that reflect the average taste 
of worker type $s$ for living in $n$ and working in $i$, respectively. 
The dispersion parameter $\epsilon$ is common to all locations.
As usual in the urban literature, larger $\epsilon$ implies less dispersion of 
preferences.


### 1.2. Firms

Each ZIP code $i$ is endowed with a representative firm that produces a tradable 
good $Y$. Following Card, Cardoso, Heining and Klein (2016),  production technology
follows

$$
Y_{i} = T_i f\left(L^\ell_{i}, L^h_{i}\right)
$$

where 
$T_i$ is a ZIP code-specific productivity shifter;
$f(\cdot)$ is twice differentiable and strictly concave; and
$L^s_{i} = \sum_n L_{ni}^s$ represents total employment of labor of type $s$, with
$L_{ni}^s$ being the measure of workers commuting from $n$ to $i$.

Firm’s $i$ optimal wage choices solve the cost minimization problem

$$
\min_{\{w^\ell_{i}, w^h_i\}} w^\ell_i L^\ell_{i}(w^\ell_i) + w^h_i L^h_{i}(w^h_i) 
\quad \text{s.t.} \quad 
T_i f\left(L^\ell_{i}(w^\ell_i), L^h_{i}(w^h_i)\right) \geq Y
$$

As we show later, because the supply functions $L^\ell_{i}(\cdot)$ and $L^h_{i}(\cdot)$ 
are upward sloping, firms in each ZIP code will set a wage offer below the marginal 
product of labor.

<!-- Notes:
- A possible extension includes adding a sector that produces non-tradable goods
-->

### 1.3. Housing

Mostly copied Perez Perez (2020)---and following much of the urban literature---. 
Land supply in location $n$ is inelastic and given by $D_n$.
Because of the Cobb-Douglas specification in the utility function, 
workers spend a fraction $1-\alpha$ of their income on housing,
which is paid to absentee landlords 
determining the price of housing in each ZIP code.


## 2.Equilibrium



\clearpage
## Appendix

### A. Derivation of indirect utility

For given $(n, i)$, $d_{n i}$, and $b_{n i \omega}$, worker's solve

$$
\begin{split}
  \max_{\{C_{n \omega}, H_{n \omega}\}} & 
              b_{n i \omega}\frac{B_i}{d_{n i}}
              \left(\frac{C_{n \omega}}{\alpha}\right)^{\alpha}
              \left(\frac{H_{n \omega}}{1-\alpha}\right)^{1-\alpha} \\
  \text{s.t.} \                         & 
              w^s_i = C_{nw} + Q_n H_{n \omega} \\
\end{split}
$$


Standard arguments imply that optimal demands are 

$$
C_{n \omega}^* = \alpha w_i^s \quad \quad 
H_{n \omega}^* = (1 - \alpha) \frac{w_i^s}{Q_n}
$$

Note that they don't depend on the worker's identity, so we can safely drop the 
$\omega$ subindex.
Replacing in the utility function we get indirect utility.

